### ISSUE TITLE
Provide way to specify a "default" command.

### ISSUE THREAD

**Issue by kashike** [EngineHub/Intake#15]
In the previous command framework (WorldEdit), there was the `NestedCommand` annotation which had a `executeBody` param. If `executeBody` was set to `true`, the method with the `NestedCommand` annotation would be processed if no arguments were provided, instead of throwing a "Please choose a sub-command." exception.

**Comment by t7seven7t** [comment]
You can get this same behavior by setting one of the aliases for a command to an empty string.
`aliases = ""`

If you have multiple aliases (for example with a help command) you may want to put the main alias first so that it shows up if you have support for auto completion:
`aliases = {"help", ""}`

**Comment by TheE** [comment]
If this is an intended feature it is probably a good idea to clearly document it in the corresponding javadocs.

If it is not, perhaps a more flexible solution would be to allow usage of custom `Dispatcher` instances by clients. These could than implement default commands as well as a more complex parsing logic, if required.

**Comment by kashike** [comment]
@t7seven7t https://github.com/sk89q/Intake/pull/16/files - that behaviour?

**Comment by t7seven7t** [comment]
More or less, there's just no obvious specification for it. It seems that the empty string method is intentional (using `String#split(String, -1)` instead of `String#split(String, 0)`) however it may have been a temporary solution til sk89q was able to create a better implementation like the one you've written up.

I'm curious as to whether people would want the default command to execute every time they misspell a sub command though. Perhaps you could add something so that the default command runs only if the user is helplessly lost (such as no arguments provided).

**Comment by TheE** [comment]
@t7seven7t At least in my use case, I want the default command to be executed every time. Given the following command structure:
* `warp add <name>`- adds a warp
* `warp remove <name>` - removes a warp
* ...
* `warp <name>` uses a warp

The last command is effectively called whenever none ob the sub-commands matches (default command). But once again, I think it is better to allow clients to modify this behaviour as desired by giving them full control over the process of resolving commands from input via custom `Dispatcher` instances.
